# Generated by Django 6.0.7 on 2026-08-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
