# Generated by Django 6.0.7 on 2026-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage_image_alter_galleryimage_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapmilestone',
            name='category',
            field=models.CharField(choices=[('trails_garden', 'Trails & Garden'), ('camping_experiences', 'Camping & Experiences'), ('visibility_bookings', 'Visibility & Bookings'), ('infrastructure', 'Infrastructure')], default='trails_garden', max_length=50),
        ),
        migrations.AlterField(
            model_name='roadmapmilestone',
            name='phase',
            field=models.IntegerField(default=1),
        ),
    ]
