# Generated by Django 6.0.7 on 2026-08-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_roadmapmilestone_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapmilestone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
